### ISSUE TITLE
Resolve networking issues

### ISSUE THREAD

**Issue by josh** [josh/qemu-rootfs#6]
The networking adapter doesn't seem to be working in any linux image or chroot I've tried.

https://github.com/josh/qemu-rootfs/blob/89e314909dded158abb2e46746dc3ef162b8648c/qemu.sh#L30

**Comment by josh** [comment]
```sh
$ docker run --rm -it --volume "$PWD/ubuntu-18.04-server-cloudimg-amd64-root.tar.xz:/rootfs.tar.xz:ro" qemu-rootfs /bin/bash

root@(none):/# apt-get update
[   10.579074] random: http: uninitialized urandom read (1 bytes read)
[   10.669294] random: http: uninitialized urandom read (1 bytes read)
[   10.756556] random: http: uninitialized urandom read (1 bytes read)
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done        
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by josh** [comment]
Putting this issue on hold for now as it will likely require distro specific configuration.

**Comment by RomanValov** [comment]
1. There is no any issues or limitations found for qemu networking running inside docker container. Already written qemu invocation command works well without changes, alternatively I've tried to run with -device e1000,id=net0. All required modifications in order to use networking should be done in configuration inside qemu guest.

2. Generally, I would split networking configuration into several stages:
a. Install additional software to manage system and networking
b. Find and load kernel modules
c. Generate interfaces configuration and manage interfaces to run
d. Deal with resolv.conf in order to provide DNS resolving

3. There two opposite approaches to perform stages:
Hardcode: init is substituted with custom script with hard-coded steps to configure networking. uses less deps (faster build, lighter image), less flexible (fixed set of devs with devnames, fixed ip settings resembling same set on qemu invocation, dhcp could be used to some degree).
Automatic: use standard init system and management tools in order to automatically configure and manage network configuration (systemd, udevd, network-manager). uses more deps (slower build, heavier image), more flexible (handles custom network configuration)

**Comment by RomanValov** [comment]
For Ubuntu qemu guest following commands should be done:

1. Pure Hardcoded:

        mount -t proc proc /proc
        mount -t sysfs sys /sys
        modprobe vfio
        modprobe vfio-pci
        modprobe virtio-net
        ip set link eth0 up
        dhclient eth0
        echo >/etc/resolv.conf << EOF
        nameserver 8.8.8.8
        nameserver 8.8.4.4
        EOF

    alternatively use nameserver defined via qemu dns option in last command:

       cat >/etc/resolv.conf << EOF
       nameserver <qemu-dns>
       EOF

    Packages required:

        apt-get install util-linux iproute2 isc-dhcp-client

    This solution should be portable across distros.

2. Slightly automated using `ifupdown` and `resolvconf`:

       mount -t proc proc /proc
       mount -t sysfs sys /sys
       modprobe vfio
       modprobe vfio-pci
       modprobe virtio-net
       echo >/etc/network/interfaces/eth0 << EOF
       iface eth0 inet dhcp
       EOF
       ifup eth0

    Packages required:

        apt-get install util-linux ifupdown ifupdown-extra resolvconf

    Please note that installation of resolvconf during `docker build` is broken and requires workarounds: https://github.com/moby/moby/issues/1297

3. More automated using `udevd` and `network-manager`:

       mount -t proc proc /proc
       mount -t sysfs sys /sys
       service dbus start
       service udevd start
       rm -f /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf
       # on bionic new netplan is used to configure wired interfaces by default
       # i hadn't familiar with it's configuration yet
       vi /etc/NetworkManager/NetworkManager.conf
       # add `dns=default` to [main] section
       service network-manager start

   Packages required:

        apt-get install util-linux udevd network-manager

    Systemd will be installed from dependencies however we still are able to boot to pure shell using `init=/bin/bash` as kernel parameter.

    In this solution udevd could assign alternative name to ethernet interface according to persistent network naming scheme which is actually less predictable. So network-manager handles unpredictable names and bring all managed ethernet interfaces to be up and dhcp-configured. I believe interface renaming could be disabled if needed.
